name: Azure Login
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  login:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
      - run: az group list -o table
          
