name: Azure Login
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  login:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY
      - run: az group list -o table
          
